### PR TITLE
Include Testserver

### PR DESCRIPTION
**Pull request by Paul1365972**
Second attempt, first time i ruined the git history...
Not sure if this is even something that should be included but i though it was kinda cool!
Adds an experimental gradle task to run the a paper server locally, its quite a nice feature for testing and this pr also contains an IntelliJ run configuration that automatically hot swaps all changes into the server

### CODE REVIEW

**Comment by Paul1365972** [comment]
Based on https://www.spigotmc.org/wiki/intellij-debug-your-plugin/

**Comment by Paul1365972** [comment]
I am not really sure if the IntelliJ run configuration should be included, as it is the default if you create a new remote run configuration

**Comment by 0ffz** [comment]
Creating a new server under each project sounds kind of annoying to work with when you have a ton of projects, especially since you might have plugins that depend on each other. I guess it's pretty neat but I don't think I see what problem you're solving. Also could you clarify what you mean by automatically hot-swapping the changes in? How's it different from just copyJar?

I do like the overall idea but I think we should have it done through docker.

**Comment by Paul1365972** [comment]
It's just a neat development thing, so you don't have to reload the plugin after changing some code, you hit build and the changes are applied immediately (no messy reloads). I really only wanted to show this option, shouldn't have made an pr for this

**Pull request closed without merging**
